name: Azure Static Web Apps CI/CD
concurrency: ci-${{ github.ref }}
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-22.04
    name: Build Job
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3.5.3
        with:
          submodules: true
        # have modified build script in package.json
        # to run prettier in checking mode, then
        # stylelint. ESLint would then be run by the
        # "next build" which will also produce build
        # output
      - name: check formatting, lint and build
        run: |
          npm install
          npm run build

      - name: Upload build output to artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: static generated site
          path: out/

  deploy_to_uat:
    needs: build
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    permissions:
      pull-requests: write
    runs-on: ubuntu-22.04
    name: Deploy Job
    steps:
      - name: Download build from artifacts
        uses: actions/download-artifact@v3.0.2
        with:
          path: out/
      - name: Deploy
        id: deploytoswa
        uses: Azure/static-web-apps-deploy@1a947af
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_POND_00D74FF03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: './out'
          api_location: '' # Api source code path - optional
          output_location: '' # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
        env:
          is_static_export: true

      - name: Post app link on PR
        uses: marocchino/sticky-pull-request-comment@v2.6.2
        with:
          message: |
            # Deployed to UAT

            ${{ steps.deploytoswa.outputs.static_web_app_url }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@1a947af
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_POND_00D74FF03 }}
          action: 'close'
