name: CI
concurrency: ci-${{ github.ref }}
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build:
    if: github.event.action != 'closed'
    runs-on: ubuntu-22.04
    name: Build
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3.5.3
        with:
          submodules: true # this attribute was part of original Azure SWA generated pipeline. Don't know why it's here

        # have modified build script in package.json
        # to run prettier in checking mode, then
        # stylelint. ESLint would then be run by the
        # "next build" which will also produce build
        # output
      - name: check formatting, lint and build
        run: |
          npm install
          npm run build

      - name: Upload build output to artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: static generated site
          path: out/

  # This is a separate job because
  # storybook tests require a special storybook build
  # So might as well run all of them in parallel with build
  # and integration tests jobs.
  storybook_tests:
    if: github.event.action != 'closed'
    runs-on: ubuntu-22.04
    name: Storybook tests
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3.5.3

      - name: Build storybook
        run: |
          npm install
          npm run build-storybook

      - name: Run test-runner for component smoke and interaction tests with coverage
        run: |
          npm run test-storybook:ci

      - name: Upload raw coverage file
        uses: actions/upload-artifact@v3.1.2
        with:
          name: test-runner coverage file
          path: coverage/storybook/coverage-storybook.json

      - name: Run accessibility tests
        # these do not generate coverage
        run: |
          npm run test-storybook-a11y:ci

  publish_test_results:
    needs: storybook_tests
    if: github.event.action != 'closed'
    runs-on: ubuntu-22.04
    name: Publish coverage and tests run report
    steps:
      - name: Download build from artifacts
        uses: actions/download-artifact@v3.0.2
        with:
          name: test-runner coverage file
          path: coverage/
      - name: Generate combined lcov coverage report
        # TODO: exclude files with extension *.stories.tsx
        # and *.stories.js and *.stories.jsx from
        # coverage report using --exclude parameter
        # of nyc report. by default anything in ./tests
        # will be excluded by nyc report
        run: |
          npx nyc report -t coverage --reporter cobertura

      - name: Upload lcov coverage file
        uses: actions/upload-artifact@v3.1.2
        with:
          name: combined cobertura coverage file
          path: coverage/cobertura-coverage.xml

      - name: Upload coverage report to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coverage/cobertura-coverage.xml
          format: cobertura

  deploy_to_uat:
    needs: build
    if: github.event.action != 'closed'
    permissions:
      pull-requests: write
    runs-on: ubuntu-22.04
    name: Deploy to UAT
    steps:
      - name: Download build from artifacts
        uses: actions/download-artifact@v3.0.2
        with:
          name: static generated site
          path: out/
      - name: Deploy
        id: deploytoswa
        uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_POND_00D74FF03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: './out'
          api_location: '' # Api source code path - optional
          output_location: '' # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
        env:
          is_static_export: true

  close_pull_request_job:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_POND_00D74FF03 }}
          action: 'close'
